#!/bin/bash
set -e

mkdir -p bin dist
git config --global --add safe.directory "${DAPPER_SOURCE:-/source}" 2>/dev/null || true
if [ -e ./scripts/$1 ]; then
    bash ./scripts/"$@"
else
    exec "$@"
fi

chown -R $DAPPER_UID:$DAPPER_GID .
