#!/usr/bin/env bash

if [ -n "${VERSION_OVERRIDE:-}" ]; then
    VERSION="${VERSION_OVERRIDE}"
    return 0
fi

DIRTY=""
if [ -n "$(git status --porcelain)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=$(git tag --points-at HEAD | head -n 1)

if [[ -z "${DIRTY}" && -n "${GIT_TAG}" ]]; then
    VERSION=${GIT_TAG}
else
    VERSION="${COMMIT}${DIRTY}"
fi

if [ -z "${ARCH:-}" ]; then
    ARCH=amd64
fi
